// Hand-maintained type boundary for the untyped JS engine (generated by tsc, then loosened
// where the inferred shapes were narrower than what the module really returns).
import type { EngineData } from "../types";
export function pdfText(v: any): string;
export function stripContent(src: any, { hiddenMC, hiddenDo, invisible }: {
    hiddenMC: any;
    hiddenDo: any;
    invisible: any;
}): {
    out: any;
    changed: boolean;
    stats: {
        oc: number;
        text: number;
        dos: number;
    };
};
export function scanPdf(bytes: Uint8Array, onProgress?: (done: number, total: number) => void): Promise<EngineData>;
export function sanitizePdf(bytes: Uint8Array, opts: EngineData, onProgress?: (msg: string) => void): Promise<EngineData>;
