// Hand-maintained type boundary for the untyped JS engine (generated by tsc, then loosened
// where the inferred shapes were narrower than what the module really returns).
import type { EngineData } from "../types";
export function labelX(align: any, pageW: any, w: any): number;
export function mulberry32(seed: any): () => number;
export function planPlacement({ pages, seal, method, align, labelHeightPt, labelWidths, rng, count, labelBottomPt, labelRotDeg }: {
    pages: any;
    seal: any;
    method: any;
    align: any;
    labelHeightPt: any;
    labelWidths: any;
    rng: any;
    count?: number;
    labelBottomPt?: number;
    labelRotDeg?: number;
}): EngineData;
export const MM: number;
